# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e0791af-58d3-4768-b619-c61377fb9d3a";
      fsType = "btrfs";
      options = [ "subvol=@/nixos-root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0e0791af-58d3-4768-b619-c61377fb9d3a";
      fsType = "btrfs";
      options = [ "subvol=@/nixos-home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0e0791af-58d3-4768-b619-c61377fb9d3a";
      fsType = "btrfs";
      options = [ "subvol=@/nixos-nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9200-4B3E";
      fsType = "vfat";
    };

  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/db69dd2d-69eb-4aca-9ca6-686787328872";
      fsType = "btrfs";
      options = [ "subvol=@/storage" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f31b525c-7cfb-4bf3-b21d-89ed34a98e04"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
